name: Build JAR in Container

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false  # Don't push the Docker image
          tags: temp-image:latest

      - name: Create dist_keycloak directory
        run: mkdir -p ./dist_keycloak

      - name: Copy JAR file from Docker image
        run: docker run --rm -v ${{ github.workspace }}/dist_keycloak:/dist temp-image:latest cp ./dist_keycloak/keycloak-theme-for-kc-22-and-above.jar /dist/keycloak-theme-for-kc-22-and-above.jar

      - name: List files in dist_keycloak
        run: ls -l ./dist_keycloak

      - name: Upload dist_keycloak artifacts to release
        uses: actions/upload-artifact@v2
        with:
          name: dist_keycloak-artifacts
          path: ./dist_keycloak/keycloak-theme-for-kc-22-and-above.jar
          if-no-files-found: warn

      - name: Add git note
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git fetch origin "refs/notes/*:refs/notes/*"
          git notes add -m "published" ${{ github.sha }}
          git push origin refs/notes/commits
