name: Docker CI

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        permissions:
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

            - name: Upload dist_keycloak artifacts to release
              uses: actions/upload-artifact@v2
              with:
                  name: dist_keycloak-artifacts
                  path: dist_keycloak/keycloak-theme-for-kc-22-and-above.jar

            - name: Add git note
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Action"
                  git fetch origin "refs/notes/*:refs/notes/*"
                  git notes add -m "published" ${{ github.sha }}
                  git push origin refs/notes/commits
